### PR TITLE
init storybook

### PR DESCRIPTION
**Pull request by nik-1207**
1. Init storybook
2.  No manual changes
3.  command executed: `npx sb init --builder webpack5`

image

### CODE REVIEW

**Comment by maneetgoyal** [comment]
> npx sb init --builder webpack5

Why `--builder webpack5` was needed? It didn't recognize the builder on its own?

Did you try `npx storybook@latest init` too? If not, try via a new PR.

**Comment by nik-1207** [comment]
> > npx sb init --builder webpack5
> 
> Why `--builder webpack5` was needed? It didn't recognize the builder on its own?
> 
> Did you try `npx storybook@latest init` too? If not, try via a new PR.

sir I used https://www.gatsbyjs.com/docs/how-to/testing/visual-testing-with-storybook/ as ref

**Comment by nik-1207** [comment]
trying ` npx storybook@latest init` via new PR

**Comment by nik-1207** [comment]
> npx storybook@latest init

@maneetgoyal  sir  storybook cli is not able to automatically detect the builder

image

**Comment by nik-1207** [comment]
Recreating

**Pull request closed without merging**
